### ISSUE TITLE
StegaStamp训练问题

### ISSUE THREAD

**Issue by fujiaixin09** [slimhappy/Stegastamp_Readme#1]
您好！我在训练StegaStamp这个项目的时候bit_acc一直没能达到作者的要求（0.95），请问您有没有遇到这个问题?可以留一下联系方式交流一下吗？可有偿。

**Comment by slimhappy** [comment]
没有，他的训练方法和论文的数据基本一致，我训练后测试的结果也是0.95，可能你需要用他提供的shell脚本里面的参数进行训练

**Comment by fujiaixin09** [comment]
您好 我使用的就是作者提供的参数 但是就是达不到作者的精度


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 下午5:40
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
没有，他的训练方法和论文的数据基本一致，我训练后测试的结果也是0.95，可能你需要用他提供的shell脚本里面的参数进行训练

**Comment by slimhappy** [comment]
数据集用的是什么？

**Comment by fujiaixin09** [comment]
mirflickr ，作者论文里面提到的数据集，10w张图片



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 下午5:42
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
数据集用的是什么？

**Comment by slimhappy** [comment]
是在tensorboard里面看到的单轮训练数据没到0.95吗？还是训练完之后使用模型对encode和decoder对大量图像进行测试发现没到0.95？如果是后者有可能是单张图像的特殊情况拉低了整体的准确率。

**Comment by fujiaixin09** [comment]
我看作者论文里面说的是最后保存的模型bit_acc要大于0.95才能正确解码 我的一直达不到作者的精度，所以无论是对编码后的图片（没有拍照 ，直接用编码好的图片）进行解码都是失败的。按照你说的应该是第二种可能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 下午5:47
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
是在tensorboard里面看到的单轮训练数据没到0.95吗？还是训练完之后使用模型对encode和decoder对大量图像进行测试发现没到0.95？如果是后者有可能是单张图像的特殊情况拉低了整体的准确率。

**Comment by slimhappy** [comment]
这是因为他的纠错编码最大只允许5个bit的错误，超过了就decode失败，数字环境下（不拍照直接用数字图像），应该比0.95高多了，结果应该在0.98以上

**Comment by fujiaixin09** [comment]
是的 但是我最后训练的模型的精确值没有达到0.95 请问您知道这个是什么原因吗 ？我看了您的“ubuntu&nbsp;20.04&nbsp;下配置StegaStamp运行环境” 除了操作系统（我是Windows）我和您的步骤几乎是一样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 下午5:56
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
这是因为他的纠错编码最大只允许5个bit的错误，超过了就decode失败，数字环境下（不拍照直接用数字图像），应该比0.95高多了，结果应该在0.98以上

**Comment by slimhappy** [comment]
windows下我也试过，加个qq聊一下吧，1874510878

**Comment by fujiaixin09** [comment]
您好 您的QQ设置不能加陌生人 可以加我QQ 2531406843




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 晚上6:07
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
windows下我也试过，加个qq聊一下吧，1874510878

**Comment by fujiaixin09** [comment]
> windows下我也试过，加个qq聊一下吧，1874510878

您好，请问像这个“”l2_loss_ramp“”什么什么ramp的参数是什么意思，在多少次迭代的时候加入噪声吗？

**Comment by slimhappy** [comment]
控制这个loss的权重在设置的数值的轮数到达最大值

**Comment by fujiaixin09** [comment]
您指的是在训练迭代次数中bit_acc最大的那个模型进行保存吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上8:14
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
控制这个loss的权重在设置的数值的轮数到达最大值

**Comment by slimhappy** [comment]
你可以看tensorboard 那里面有这个l2_loss你会发现它一开始并不是设定的值，会随着训练迭代次数的增大而增大，直到到你的设定值，到达设定值的迭代轮数就是这个ramp

**Comment by fujiaixin09** [comment]
嗯嗯 好的理解了 谢谢你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimhappy/Stegastamp_Readme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上8:55
收件人:&nbsp;"slimhappy/Stegastamp_Readme"<Stegastamp_Readme@noreply.github.com&gt;;
抄送:&nbsp;"🍂"<2531406843@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [slimhappy/Stegastamp_Readme] StegaStamp训练问题 (#1)





 
你可以看tensorboard 那里面有这个l2_loss你会发现它一开始并不是设定的值，会随着训练迭代次数的增大而增大，直到到你的设定值，到达设定值的迭代轮数就是这个ramp
